stages:
- build

build_image:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/zumbrunnen/unifi:latest .
    - docker push $CI_REGISTRY/zumbrunnen/unifi:latest
  only:
    - master
